version: '3.8'

services:
  db:
    image: postgres:15
    container_name: zeine_postgres
    environment:
      POSTGRES_DB: zeine_test
      POSTGRES_USER: zeine_user
      POSTGRES_PASSWORD: zeine_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
